server:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
  retention: 12h
  scrapeInterval: 15s

alertmanager:
  enabled: false

pushgateway:
  enabled: false

nodeExporter:
  enabled: true
