apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
        - name: java-app
          image: openjdk:17-jdk-slim
          ports:
            - containerPort: 8080
