apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: 'https://github.com/tuusuario/platform-lab-local'
    targetRevision: HEAD
    path: services/microservice-a
  project: default
